### ISSUE TITLE
Hi here is the text 

### ISSUE THREAD

**Issue by raviten** [UbuntuForums/wireless-info#1]
http://paste.ubuntu.com/11537036/

Please review

**Comment by UbuntuForumsCouncil** [comment]
The contact us link you used to send your email is for contacting forum
admins regarding problems with your forum account. We cannot provide
technical support from the mailing list.

If you need help from forum members, please go to a sub-forum that is
relevant  - I suggest the Networking & Wireless
http://ubuntuforums.org/forumdisplay.php?f=336. Click on the orange Post
New Thread button to post your question.

slickymaster
Ubuntu Forums Council
