### ISSUE TITLE
Just a dumb question: Does this tool work under Debian too?

### ISSUE THREAD

**Issue by sahwar** [UbuntuForums/wireless-info#3]
Sorry if this is a dumb question, but here it goes:

Does this tool work under Debian too?

Thanks in advance for your reply.

P.S. LOL, I'm so stupid, it's a bash shell script, of course it should work under Debian... I'll soon test it under Debian just to make sure that it does work.

**Comment by UbuntuForumsCouncil** [comment]
Hello

Please be advised that this mailing list is for contacting the Forum
Council regarding issues with your forums account, not for soliciting
support.

You would be better served by starting a thread in the forums,
probably the Networking
& Wireless https://ubuntuforums.org/forumdisplay.php?f=336 forum would be
fine for your query.

Regards,
slickymaster
