### ISSUE TITLE
Add Netplan Support

### ISSUE THREAD

**Issue by powersj** [UbuntuForums/wireless-info#5]
Starting in 17.10 Netplan became the default method for configuring networks. For folks seeking help, using the wireless-info script it should also include details on any configuration of netplan.

My proposal would include printing any configuration files found in /[etc|run|lib]/netplan/*.yaml, however I understand that sensitive data like MAC and IP addresses are masked. Given these are YAML files it might be easy, but it might also simply be enough to print the filenames in these directories.

This way if any of the default files (e.g. 01-network-manager-all.yaml, /etc/netplan/01-network-manager-all.yaml, or /etc/netplan/50-cloud-init.yaml) it aids in debug and triage and if any non-default files are there additional questions or queries can at least be made to the reporter.

**Comment by wildmanne39** [comment]
I just wanted to let you know that the changes are going to be made, it may take a little time to get them done. 

Thanks for the suggestion.
