### ISSUE TITLE
Script missing interfaces info when using partials

### ISSUE THREAD

**Issue by jonathannlittle** [UbuntuForums/wireless-info#6]
Your script records the /etc/network/interfaces configuration but omits including anything when using partials in  /etc/network/interfaces.d/ Suggest adding some code in your interfaces section like:

`printf "\n##### interfaces ########################\n\n"
sed '/^#/d;s/^wpa-psk [[:graph:]]\+/wpa-psk <WPA key removed>/' /etc/network/interfaces

#Add partials if they exist 
IF_PARTIALS=$(awk '/^source/ { print $2 }' /etc/network/interfaces)
if [ -n "$IF_PARTIALS" ]; then
	for f in $(ls $IF_PARTIALS); do
	    printf "\n# $f\n"
	    sed '/^#/d;s/^wpa-psk [[:graph:]]\+/wpa-psk <WPA key removed>/' $f
	done 
fi
`

**Comment by UbuntuForumsCouncil** [comment]
Hello jonathannlittle.

Thanks for your input. A commit has just been made fixing the issue you raised.

Regards
